config/routes.rb
Events::Application.routes.draw do
  get "pages/home"

  get "pages/contact"

  resources :organizers

  resources :locations

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :location, :name, :organizer
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :street
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  attr_accessible :name, :office
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizers }
    end
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
    @organizer = Organizer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organizer }
    end
  end

  # GET /organizers/new
  # GET /organizers/new.json
  def new
    @organizer = Organizer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organizer }
    end
  end

  # GET /organizers/1/edit
  def edit
    @organizer = Organizer.find(params[:id])
  end

  # POST /organizers
  # POST /organizers.json
  def create
    @organizer = Organizer.new(params[:organizer])

    respond_to do |format|
      if @organizer.save
        format.html { redirect_to @organizer, notice: 'Organizer was successfully created.' }
        format.json { render json: @organizer, status: :created, location: @organizer }
      else
        format.html { render action: "new" }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizers/1
  # PUT /organizers/1.json
  def update
    @organizer = Organizer.find(params[:id])

    respond_to do |format|
      if @organizer.update_attributes(params[:organizer])
        format.html { redirect_to @organizer, notice: 'Organizer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizers/1
  # DELETE /organizers/1.json
  def destroy
    @organizer = Organizer.find(params[:id])
    @organizer.destroy

    respond_to do |format|
      format.html { redirect_to organizers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :organizer %><br />
    <%= f.text_field :organizer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h3>Editing event</h3>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h3>The list of the events is:</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Location</th>
    <th>Organizer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>



<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.date %></td>
    <td><%= event.location %></td>
    <td><%= event.organizer %></td>
    <td><%= link_to 'Info', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<p>Create a new event:<%= link_to 'New Event', new_event_path %></p>

app/views/events/new.html.erb
<h3>New event</h3>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Organizer:</b>
  <%= @event.organizer %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/meniu' %>
<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>City</th>
    <th>Street</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.city %></td>
    <td><%= location.street %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>Street:</b>
  <%= @location.street %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/organizers/_form.html.erb
<%= form_for(@organizer) do |f| %>
  <% if @organizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organizer.errors.count, "error") %> prohibited this organizer from being saved:</h2>

      <ul>
      <% @organizer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :office %><br />
    <%= f.text_field :office %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizers/edit.html.erb
<h1>Editing organizer</h1>

<%= render 'form' %>

<%= link_to 'Show', @organizer %> |
<%= link_to 'Back', organizers_path %>

app/views/organizers/index.html.erb
<h1>Listing organizers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Office</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizers.each do |organizer| %>
  <tr>
    <td><%= organizer.name %></td>
    <td><%= organizer.office %></td>
    <td><%= link_to 'Show', organizer %></td>
    <td><%= link_to 'Edit', edit_organizer_path(organizer) %></td>
    <td><%= link_to 'Destroy', organizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organizer', new_organizer_path %>

app/views/organizers/new.html.erb
<h1>New organizer</h1>

<%= render 'form' %>

<%= link_to 'Back', organizers_path %>

app/views/organizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organizer.name %>
</p>

<p>
  <b>Office:</b>
  <%= @organizer.office %>
</p>


<%= link_to 'Edit', edit_organizer_path(@organizer) %> |
<%= link_to 'Back', organizers_path %>

app/views/pages/contact.html.erb
<h3>Contact</h3>
<table>
<tr>
  <td>Last name:</td><td><input type="text" name="nume"></td>
</tr>
<tr>
  <td>First name:</td><td><input type="text" name="prenume"></td>
</tr>
<tr>
<td>Email:</td> <td><input type="text" name="nume"></td>
</tr>
<tr>
<td>Message:</td> <td><input type="text" name="nume"></td>
</tr>
<tr>
  <td><input type="submit" name="trimite"></td>
  <td><input type="reset" name="sterge"></td>
</tr>
</table>

app/views/pages/home.html.erb
<h3>Bine ați venit!</h3>
<p>Ne bucurăm de alegerea pe care a-ți făcut-o de a vizita site-ul nostru!<br /> Pentru a vizualiza lista de evenimente disponibile alegeți din meniu opțiunea "Events"</p>

app/views/shared/_meniu.html.erb
<div class="meniu">
	<ul>
		<li>
			<%= link_to 'Home', '/pages/home' %>
		</li>
		<li>
			<%= link_to 'Events', '/events' %>
		</li>
		<li>
		  <%= link_to 'Contact', '/pages/contact' %>
		</li>

	</ul>

</div>